//! Generated SDK client adapter — bridges AppContext to the co-generated SDK.
//!
//! Auto-generated by @fern-api/cli-generator. Do not edit by hand.

#![allow(dead_code)]

use std::future::Future;
use std::pin::Pin;
use std::sync::Arc;

use fern_cli_sdk::error::CliError;
use fern_cli_sdk::openapi::AppContext;
use fern_cli_sdk::sdk_executor::{CliExecutor, SdkError, SdkRequestExecutor};

// ---------------------------------------------------------------------------
// Executor adapter: CliExecutor → SDK RequestExecutor
// ---------------------------------------------------------------------------

struct CliExecutorAdapter(Arc<CliExecutor>);

impl videogen_sdk::RequestExecutor for CliExecutorAdapter {
    fn execute(
        &self,
        request: reqwest::Request,
    ) -> Pin<
        Box<
            dyn Future<Output = Result<reqwest::Response, Box<dyn std::error::Error + Send + Sync>>>
                + Send
                + '_,
        >,
    > {
        Box::pin(async move {
            SdkRequestExecutor::execute(&*self.0, request)
                .await
                .map_err(|e| Box::new(e) as Box<dyn std::error::Error + Send + Sync>)
        })
    }
}

// ---------------------------------------------------------------------------
// client — construct a fully-wired SDK root client
// ---------------------------------------------------------------------------

/// Build the SDK root client from the CLI's runtime context.
///
/// The returned client routes all HTTP through the CLI's executor, so
/// it inherits auth, retries, TLS, and global headers automatically.
pub fn client(ctx: &AppContext) -> videogen_sdk::api::ApiClient {
    let executor = ctx.build_sdk_executor();
    let adapter = Arc::new(CliExecutorAdapter(executor));
    let config = videogen_sdk::ClientConfig::default();
    let http_client = videogen_sdk::HttpClient::with_executor(
        adapter as Arc<dyn videogen_sdk::RequestExecutor>,
        config.clone(),
    );
    videogen_sdk::api::ApiClient {
        config,
        workflows: videogen_sdk::api::WorkflowsClient { http_client: http_client.clone() },
        projects: videogen_sdk::api::ProjectsClient { http_client: http_client.clone() },
        tools: videogen_sdk::api::ToolsClient { http_client: http_client.clone() },
        files: videogen_sdk::api::FilesClient { http_client: http_client.clone() },
        entities: videogen_sdk::api::EntitiesClient { http_client: http_client.clone() },
        text: videogen_sdk::api::TextClient { http_client: http_client.clone() },
        resources: videogen_sdk::api::ResourcesClient { http_client: http_client.clone() },
        webhooks: videogen_sdk::api::WebhooksClient { http_client: http_client.clone() },
        account: videogen_sdk::api::AccountClient { http_client: http_client.clone() },
    }
}

// ---------------------------------------------------------------------------
// block_on — async SDK call → sync handler result
// ---------------------------------------------------------------------------

/// Execute an async SDK operation from a synchronous custom-command handler.
///
/// Bridges the SDK's `ApiError` into the CLI's `CliError` so `?` works
/// naturally in handler bodies.
pub fn block_on<F, T>(future: F) -> Result<T, CliError>
where
    F: Future<Output = Result<T, videogen_sdk::ApiError>>,
{
    tokio::task::block_in_place(|| {
        let handle = tokio::runtime::Handle::current();
        handle.block_on(future).map_err(convert_api_error)
    })
}

fn convert_api_error(e: videogen_sdk::ApiError) -> CliError {
    match e {
        videogen_sdk::ApiError::Http { status, message } => CliError::Api {
            code: status,
            message,
            reason: http_status_reason(status).to_string(),
        },
        videogen_sdk::ApiError::Network(err) => {
            CliError::Other(anyhow::anyhow!("SDK network error: {err}"))
        }
        videogen_sdk::ApiError::Executor(boxed) => match boxed.downcast::<SdkError>() {
            Ok(sdk_error) => sdk_error.into_cli_error(),
            Err(other) => CliError::Other(anyhow::anyhow!("SDK executor error: {other}")),
        },
        other => CliError::Other(anyhow::anyhow!("SDK error: {other}")),
    }
}

fn http_status_reason(status: u16) -> &'static str {
    match status {
        400 => "badRequest",
        401 => "unauthorized",
        403 => "forbidden",
        404 => "notFound",
        408 => "requestTimeout",
        409 => "conflict",
        429 => "tooManyRequests",
        500 => "internalServerError",
        502 => "badGateway",
        503 => "serviceUnavailable",
        504 => "gatewayTimeout",
        _ => "httpError",
    }
}
